kind: pipeline
type: kubernetes
name: production

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: sakyavarro/blog
      tags: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password

trigger:
  branch:
    - master
    - staging
    - test*

