language: node_js

sudo: required

node_js: stable

branches:
  only:
    - deploy

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

after_script:
  - git config --global user.name "varro-travis"
  - git config --global user.email "542109010@qq.com"
  - sed -i "s/gh_token/${GITHUB_REPO_TOKEN}/g" ./_config.yml
  - hexo deploy
