language: node_js

sudo: required

node_js: stable

addons:
  ssh_known_hosts: 118.24.102.34

branches:
  only:
    - deploy

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli
  - openssl aes-256-cbc -K $encrypted_162432d46384_key -iv $encrypted_162432d46384_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - ls -al /tmp/
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  - git config --global user.name "varro-travis"
  - git config --global user.email "542109010@qq.com"
  - sed -i "s/gh_token/${GITHUB_REPO_TOKEN}/g" ./_config.yml
  - hexo deploy

after_script:
  - ssh deployer@sakyavarro.cn -o stricthostkeychecking=no -i /tmp/deploy_rsa 'cd /var/www
    && rm -rf hexo && git clone https://github.com/SakyaVarro/sakyavarro.github.io.git hexo && chmod -R 777 hexo && echo done && exit'

