language: node_js

node_js: stable

branches:
  only:
    - deploy

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

env:
  global:
    - GITHUB_REPO: github.com/SakyaVarro/SakyaVarro.github.io

before_install:
  - git config --global user.name "varro-travis"
  - git config --global user.email "542109010@qq.com"
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g hexo-cli

install:
  - yarn

script:
  - git pull
  - git checkout deploy
  - hexo clean
  - hexo g
  - git status
  - git add --all
  - git commit -m "Travis CI Auto Builder"
  - git checkout master
  - git merge deploy
  - git status
  - git push  "https://${GITHUB_REPO_TOKEN}@${GITHUB_REPO}" master:master
  - git status